import { Role, type User, type Ward, type Contract, ContractStatus } from "./types";

export const INITIAL_USERS: User[] = [
  {
    id: 1,
    username: "admin",
    password: "admin123",
    fullName: "Quản trị viên",
    role: Role.Admin,
  },
  {
    id: 2,
    username: "nhanvien01",
    password: "user123",
    fullName: "Nhân viên A",
    role: Role.User,
  },
];

export const INITIAL_WARDS: Ward[] = [
    { id: 1, wardName: "Phường Bình Lộc", wardCode: "BL" },
    { id: 2, wardName: "Phường Bảo Vinh", wardCode: "BV" },
    { id: 3, wardName: "Phường Xuân Lập", wardCode: "XL" },
    { id: 4, wardName: "Phường Hàng Gòn", wardCode: "HG" },
    { id: 5, wardName: "Phường Long Khánh", wardCode: "LK" },
];

export const INITIAL_CONTRACTS: Contract[] = [
  {
    id: 1,
    customerName: "Nguyễn Văn An",
    wardId: 1,
    createdAt: "2024-01-15T10:00:00Z",
    status: ContractStatus.Completed,
    mapSheetNumber: 10,
    plotNumber: 101,
    contractNumber: "01/24BL.HĐ.VPĐKLK",
    notes: "Đã hoàn tất thủ tục.",
  },
  {
    id: 2,
    customerName: "Trần Thị Bích",
    wardId: 2,
    createdAt: "2024-02-20T11:30:00Z",
    status: ContractStatus.Completed,
    mapSheetNumber: 12,
    plotNumber: 55,
    contractNumber: "02/24BV.HĐ.VPĐKLK",
  },
  {
    id: 3,
    customerName: "Lê Hoàng Cường",
    wardId: 3,
    createdAt: "2024-03-05T09:15:00Z",
    status: ContractStatus.Completed,
    mapSheetNumber: 5,
    plotNumber: 23,
    contractNumber: "03/24XL.HĐ.VPĐKLK",
    notes: "Khách hàng yêu cầu gấp."
  },
  {
    id: 4,
    customerName: "Phạm Minh Dũng",
    wardId: 4,
    createdAt: "2024-03-10T14:00:00Z",
    status: ContractStatus.Cancelled,
    mapSheetNumber: 22,
    plotNumber: 150,
    contractNumber: "04/24HG.HĐ.VPĐKLK",
    cancellationReason: "Khách hàng không cung cấp đủ giấy tờ.",
  },
  {
    id: 5,
    customerName: "Võ Thị Em",
    wardId: 5,
    createdAt: "2024-04-01T16:45:00Z",
    status: ContractStatus.Completed,
    mapSheetNumber: 18,
    plotNumber: 88,
    contractNumber: "05/24LK.HĐ.VPĐKLK",
  },
  {
    id: 6,
    customerName: "Đặng Gia Hân",
    wardId: 1,
    createdAt: "2024-04-15T08:00:00Z",
    status: ContractStatus.Processing,
    mapSheetNumber: 11,
    plotNumber: 112,
    contractNumber: "06/24BL.HĐ.VPĐKLK",
    notes: "Chờ bổ sung hồ sơ."
  },
  {
    id: 7,
    customerName: "Hồ Văn Kiên",
    wardId: 2,
    createdAt: "2024-05-02T13:20:00Z",
    status: ContractStatus.Processing,
    mapSheetNumber: 13,
    plotNumber: 60,
    contractNumber: "07/24BV.HĐ.VPĐKLK",
  },
  {
    id: 8,
    customerName: "Bùi Thị Lan",
    wardId: 3,
    createdAt: "2024-05-10T10:10:00Z",
    status: ContractStatus.Processing,
    mapSheetNumber: 6,
    plotNumber: 30,
    contractNumber: "08/24XL.HĐ.VPĐKLK",
    notes: "Đã liên hệ khách hàng."
  },
  {
    id: 9,
    customerName: "Trương Minh Nam",
    wardId: 4,
    createdAt: "2024-05-20T15:00:00Z",
    status: ContractStatus.Processing,
    mapSheetNumber: 23,
    plotNumber: 155,
    contractNumber: "09/24HG.HĐ.VPĐKLK",
  },
  {
    id: 10,
    customerName: "Phan Thị Oanh",
    wardId: 5,
    createdAt: "2024-06-01T09:00:00Z",
    status: ContractStatus.Processing,
    mapSheetNumber: 19,
    plotNumber: 92,
    contractNumber: "10/24LK.HĐ.VPĐKLK",
  },
  {
    id: 11,
    customerName: "Hoàng Văn Phát",
    wardId: 1,
    createdAt: "2023-11-05T14:30:00Z",
    status: ContractStatus.Completed,
    mapSheetNumber: 9,
    plotNumber: 99,
    contractNumber: "01/23BL.HĐ.VPĐKLK",
  },
  {
    id: 12,
    customerName: "Mai Anh Quân",
    wardId: 2,
    createdAt: "2023-11-15T11:00:00Z",
    status: ContractStatus.Cancelled,
    mapSheetNumber: 11,
    plotNumber: 50,
    contractNumber: "02/23BV.HĐ.VPĐKLK",
    cancellationReason: "Thông tin thửa đất không chính xác.",
  },
  {
    id: 13,
    customerName: "Dương Thị Rosi",
    wardId: 3,
    createdAt: "2023-12-01T16:00:00Z",
    status: ContractStatus.Completed,
    mapSheetNumber: 4,
    plotNumber: 20,
    contractNumber: "03/23XL.HĐ.VPĐKLK",
  },
  {
    id: 14,
    customerName: "Ngô Thành Tín",
    wardId: 4,
    createdAt: "2023-12-10T09:45:00Z",
    status: ContractStatus.Completed,
    mapSheetNumber: 21,
    plotNumber: 145,
    contractNumber: "04/23HG.HĐ.VPĐKLK",
  },
  {
    id: 15,
    customerName: "Lại Uyển Vy",
    wardId: 5,
    createdAt: "2023-12-25T10:30:00Z",
    status: ContractStatus.Completed,
    mapSheetNumber: 17,
    plotNumber: 80,
    contractNumber: "05/23LK.HĐ.VPĐKLK",
    notes: "Hồ sơ lưu trữ tại kho A."
  },
  {
    id: 16,
    customerName: "Bành Thị Tuyết",
    wardId: 2,
    createdAt: "2025-01-10T09:00:00Z",
    status: ContractStatus.Processing,
    mapSheetNumber: 30,
    plotNumber: 200,
    contractNumber: "01/25BV.HĐ.VPĐKLK",
  },
  {
    id: 17,
    customerName: "Chung Vô Diệm",
    wardId: 4,
    createdAt: "2025-01-12T11:00:00Z",
    status: ContractStatus.Processing,
    mapSheetNumber: 32,
    plotNumber: 205,
    contractNumber: "02/25HG.HĐ.VPĐKLK",
  },
  {
    id: 18,
    customerName: "Đinh Tiên Hoàng",
    wardId: 1,
    createdAt: "2025-01-20T14:30:00Z",
    status: ContractStatus.Processing,
    mapSheetNumber: 35,
    plotNumber: 210,
    contractNumber: "03/25BL.HĐ.VPĐKLK",
    notes: "Hẹn khách ngày 25/01/2025.",
  },
  {
    id: 19,
    customerName: "Âu Dương Phong",
    wardId: 5,
    createdAt: "2025-02-05T08:45:00Z",
    status: ContractStatus.Processing,
    mapSheetNumber: 40,
    plotNumber: 220,
    contractNumber: "04/25LK.HĐ.VPĐKLK",
  },
  {
    id: 20,
    customerName: "Quách Tĩnh",
    wardId: 3,
    createdAt: "2025-02-11T10:15:00Z",
    status: ContractStatus.Completed,
    mapSheetNumber: 42,
    plotNumber: 225,
    contractNumber: "05/25XL.HĐ.VPĐKLK",
  },
  {
    id: 21,
    customerName: "Hoàng Dung",
    wardId: 2,
    createdAt: "2025-02-18T16:00:00Z",
    status: ContractStatus.Processing,
    mapSheetNumber: 45,
    plotNumber: 230,
    contractNumber: "06/25BV.HĐ.VPĐKLK",
  },
  {
    id: 22,
    customerName: "Dương Quá",
    wardId: 4,
    createdAt: "2025-02-25T09:30:00Z",
    status: ContractStatus.Cancelled,
    mapSheetNumber: 48,
    plotNumber: 235,
    contractNumber: "07/25HG.HĐ.VPĐKLK",
    cancellationReason: "Khách hàng rút hồ sơ.",
  },
  {
    id: 23,
    customerName: "Tiểu Long Nữ",
    wardId: 1,
    createdAt: "2025-03-02T13:00:00Z",
    status: ContractStatus.Processing,
    mapSheetNumber: 50,
    plotNumber: 240,
    contractNumber: "08/25BL.HĐ.VPĐKLK",
    notes: "Chờ kết quả đo đạc.",
  },
  {
    id: 24,
    customerName: "Lý Mạc Sầu",
    wardId: 5,
    createdAt: "2025-03-10T11:20:00Z",
    status: ContractStatus.Processing,
    mapSheetNumber: 55,
    plotNumber: 250,
    contractNumber: "09/25LK.HĐ.VPĐKLK",
  },
  {
    id: 25,
    customerName: "Doãn Chí Bình",
    wardId: 3,
    createdAt: "2025-03-15T15:55:00Z",
    status: ContractStatus.Processing,
    mapSheetNumber: 60,
    plotNumber: 260,
    contractNumber: "10/25XL.HĐ.VPĐKLK",
  }
];
